### ISSUE TITLE
iptables-restore v1.8.10 (nf_tables)

### ISSUE THREAD

**Issue by unlimmitted** [yury-sannikov/amnezia-wg-docker#6]
Hi, after a break I'm trying to set up amnezia again, I again encountered the problem "iptables-restore v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument", can you tell me what to do?

`
Warning: `/etc/amnezia/amneziawg/wg0.conf' is world accessible
[#] ip link add wg0 type amneziawg
Error: Unknown device type.
[!] Missing WireGuard (Amnezia VPN) kernel module. Falling back to slow userspace implementation.
[#] amneziawg-go wg0
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] awg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.1.3/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] awg set wg0 fwmark 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
Warning: Extension addrtype revision 0 not supported, missing kernel module?
Warning: Extension comment revision 0 not supported, missing kernel module?
iptables-restore v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
`

**Comment by wiktorbgu** [comment]
My config vpn WARP for mikrotik:
```
[Interface]
PrivateKey = your-key=
Jc = 10
Jmin = 50
Jmax = 1000
S1 = 0
S2 = 0
Address = 172.16.0.2
DNS = 1.1.1.1, 1.0.0.1
MTU=1280

# Replace 192.168.254.1 with your router IP address in the bridge where the container is located
# Here is the IP of the Endpoint
PreUp = ip route add 162.159.193.5 via 192.168.254.1 dev eth0
# exclude local networks
PreUp = ip route add 10.0.0.0/8 via 192.168.254.1 dev eth0
PreUp = ip route add 172.16.0.0/12 via 192.168.254.1 dev eth0
PreUp = ip route add 192.168.0.0/16 via 192.168.254.1 dev eth0

[Peer]
PublicKey = your-key=
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
Endpoint = 162.159.193.5:2408
PersistentKeepalive = 25
```

**Comment by unlimmitted** [comment]
Thank you very much, apparently I was missing PreUp😁😁😁😁😁😁😁😁😁😁😁
